[package]
name = "graphity"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
miette = "5.10.0"
once_cell = "1.19.0"
petgraph = { version = "0.6.4", default-features = false, features = [
	"serde-1",
] }
regex = "1.10.3"
semver = { version = "1.0.21", features = ["serde"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_yaml = "0.9.30"
starbase_utils = { version = "0.3.11", default-features = false, features = [
	"glob",
	"json",
	"yaml",
] }
